=== ESTG-PEI/2022_2023/ExemploEmail/emailTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    
    <xs:element name="emails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="email" type="emailType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="emailType">
        <xs:sequence>
            <xs:element name="to" type="emailDataType"></xs:element>
            <xs:element name="from" type="emailDataType"></xs:element>
            <xs:element name="heading" type="xs:string"></xs:element>
            <xs:element name="date"  minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:date">
                            <xs:attribute name="format" type="xs:string" fixed="yyyy-mm-dd" use="required"></xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="body" type="xs:string"></xs:element>
        </xs:sequence>
        <xs:attribute name="type" type="typeType" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:simpleType name="typeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Professional"></xs:enumeration>
            <xs:enumeration value="Personal"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="emailDataType">
        <xs:restriction base="xs:string">
            <!-- Referência web: https://www.computerhope.com/unix/regex-quickref.htm, com exemplos muito úteis !-->
            <!-- site útil: https://regexr.com, para testar expressões regulares !-->
            <xs:pattern value="[^@]+@[^\.]+\..+"></xs:pattern>
        </xs:restriction>  
    </xs:simpleType>
    
</xs:schema>

=== ESTG-PEI/2022_2023/ExemploEmail/ExemploEmail.xml
<?xml version="1.0" encoding="UTF-8"?>
<emails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="emailTypes.xsd" >
    <email type = "Personal">
        <to>Tove@gmail.com</to>
        <from>Jani@gmail.com</from>
        <heading>Reunião</heading>
        <date format = "yyyy-mm-dd">2017-10-02</date>
        <body>Olá, tudo bem?</body>
    </email>
    <email type = "Personal">
        <to>Tove@gmail.com</to>
        <from>Jani@gmail.com</from>
        <heading>Reunião</heading>
        <date format = "yyyy-mm-dd">2017-10-02</date>
        <body>Olá, tudo bem?</body>
    </email>
    <email type = "Professional">
        <to>Tove@gmail.com</to>
        <from>Jani@gmail.com</from>
        <heading>Reunião</heading>
        <date format = "yyyy-mm-dd">2017-10-02</date>
        <body>Olá, tudo bem?</body>
    </email>
    <email type = "Personal">
        <to>Tove@gmail.com</to>
        <from>Jani@gmail.com</from>
        <heading>Reunião</heading>
        <date format = "yyyy-mm-dd">2017-10-02</date>
        <body>Olá, tudo bem?</body>
    </email>
</emails>
